
topic:
  partitions: 3
  replicas: 1

spring:
  kafka:
    topic: second_topic
    bootstrap-servers: localhost:9092
    
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 0
        retries: 10
        retry.backoff.ms: 1000
        spring.json.trusted.packages: '*'
    admin:
      properties:
        bootstrap.servers: localhost:9092